<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunnyActivities.Infrastructure\FunnyActivities.Infrastructure.csproj" />
    <ProjectReference Include="..\FunnyActivities.Application\FunnyActivities.Application.csproj" />
    <ProjectReference Include="..\FunnyActivities.Domain\FunnyActivities.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Minio" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>

</Project>