// <auto-generated />
using System;
using FunnyActivities.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FunnyActivities.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250924150000_AddSurveySystemEntities")]
    partial class AddSurveySystemEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Existing entities are already defined in the model snapshot
            // We only need to add the new survey system entities

            modelBuilder.Entity("FunnyActivities.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartDate");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("FunnyActivities.Domain.Entities.SurveyActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyId", "Order")
                        .IsUnique();

                    b.ToTable("SurveyActivities");
                });

            modelBuilder.Entity("FunnyActivities.Domain.Entities.SurveyParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ParticipatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.HasIndex("UserId");

                    b.HasIndex("SurveyId", "UserId")
                        .IsUnique();

                    b.ToTable("SurveyParticipants");
                });

            modelBuilder.Entity("FunnyActivities.Domain.Entities.SurveyVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SurveyActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VoteValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurveyActivityId");

                    b.HasIndex("SurveyId");

                    b.HasIndex("UserId");

                    b.HasIndex("SurveyId", "SurveyActivityId", "UserId")
                        .IsUnique();

                    b.ToTable("SurveyVotes");
                });

            // Define relationships for new entities
            modelBuilder.Entity("FunnyActivities.Domain.Entities.Survey", b =>
                {
                    b.HasOne("FunnyActivities.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("FunnyActivities.Domain.Entities.SurveyActivity", b =>
                {
                    b.HasOne("FunnyActivities.Domain.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FunnyActivities.Domain.Entities.Survey", "Survey")
                        .WithMany("SurveyActivities")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FunnyActivities.Domain.Entities.SurveyParticipant", b =>
                {
                    b.HasOne("FunnyActivities.Domain.Entities.Survey", "Survey")
                        .WithMany("SurveyParticipants")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FunnyActivities.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FunnyActivities.Domain.Entities.SurveyVote", b =>
                {
                    b.HasOne("FunnyActivities.Domain.Entities.SurveyActivity", "SurveyActivity")
                        .WithMany("SurveyVotes")
                        .HasForeignKey("SurveyActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FunnyActivities.Domain.Entities.Survey", "Survey")
                        .WithMany("SurveyVotes")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FunnyActivities.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyActivity");

                    b.Navigation("Survey");

                    b.Navigation("User");
                });

            // Add navigation properties to existing entities
            modelBuilder.Entity("FunnyActivities.Domain.Entities.Survey", b =>
                {
                    b.Navigation("SurveyActivities");

                    b.Navigation("SurveyParticipants");

                    b.Navigation("SurveyVotes");
                });

            modelBuilder.Entity("FunnyActivities.Domain.Entities.SurveyActivity", b =>
                {
                    b.Navigation("SurveyVotes");
                });

            // Add check constraint for vote values
            modelBuilder.Entity("FunnyActivities.Domain.Entities.SurveyVote", b =>
                {
                    b.HasCheckConstraint("CK_SurveyVotes_VoteValue_Range", "VoteValue >= 1 AND VoteValue <= 5");
                });
#pragma warning restore 612, 618
        }
    }
}